"""initial schema

Revision ID: 34a8b230b103
Revises: 
Create Date: 2026-06-24 15:14:15.309203
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '34a8b230b103'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authority_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vet_department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipalities_city_name'), ['city_name'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_private', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_number_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_phone'), ['phone'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'field_worker', 'viewer', name='userrole'), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('dog', 'person', 'surrender_case', 'adoption_case', 'adoption_lead', 'ownership_transfer', name='entitytype'), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('ownership_transfer_form', 'receiver_approval_form', 'id_card_surrenderer', 'id_card_receiver', 'adopter_with_dog_photo', 'authority_submission', 'authority_confirmation', 'other', name='documenttype'), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_person_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'approved', 'rejected', name='documentstatus'), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_related_entity_type'), ['related_entity_type'], unique=False)

    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='doggender'), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large', 'xlarge', name='dogsize'), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chip_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=True),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=True),
    sa.Column('medical_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('behavior_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('good_with_children', sa.Boolean(), nullable=True),
    sa.Column('good_with_dogs', sa.Boolean(), nullable=True),
    sa.Column('good_with_cats', sa.Boolean(), nullable=True),
    sa.Column('suitable_for_apartment', sa.Boolean(), nullable=True),
    sa.Column('suitable_for_first_time_owner', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_surrender', 'in_facility', 'available_for_adoption', 'reserved', 'adopted', 'inactive', name='dogstatus'), nullable=False),
    sa.Column('current_location_type', sa.Enum('home', 'facility', 'adopted', name='locationtype'), nullable=False),
    sa.Column('current_owner_person_id', sa.Integer(), nullable=True),
    sa.Column('public_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_owner_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dogs_chip_number'), ['chip_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dogs_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('whatsapp', 'email', 'sms', 'system', name='messagechannel'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='messagedirection'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='messagestatus'), nullable=False),
    sa.Column('provider_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_person_id'), ['person_id'], unique=False)

    op.create_table('signature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('dog', 'person', 'surrender_case', 'adoption_case', 'adoption_lead', 'ownership_transfer', name='entitytype'), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=False),
    sa.Column('signer_person_id', sa.Integer(), nullable=False),
    sa.Column('signature_type', sa.Enum('surrenderer', 'receiver', 'adopter', name='signaturetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'signed', 'declined', 'expired', name='signaturestatus'), nullable=False),
    sa.Column('sign_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('provider_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signer_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_requests_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_related_entity_type'), ['related_entity_type'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_type', sa.Enum('dog', 'person', 'surrender_case', 'adoption_case', 'adoption_lead', 'ownership_transfer', name='entitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='taskpriority'), nullable=False),
    sa.Column('is_followup', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_related_entity_type'), ['related_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('adoption_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('preferred_size', sa.Enum('small', 'medium', 'large', 'xlarge', name='dogsize'), nullable=True),
    sa.Column('preferred_breed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=True),
    sa.Column('has_other_dogs', sa.Boolean(), nullable=True),
    sa.Column('home_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('experience_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hours_alone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_messages', sa.Boolean(), nullable=False),
    sa.Column('consent_privacy', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'matched', 'converted', 'closed', name='adoptionleadstatus'), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adoption_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_leads_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_leads_status'), ['status'], unique=False)

    op.create_table('dog_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dog_photos_dog_id'), ['dog_id'], unique=False)

    op.create_table('ownership_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('from_person_id', sa.Integer(), nullable=True),
    sa.Column('to_person_id', sa.Integer(), nullable=True),
    sa.Column('from_authority_id', sa.Integer(), nullable=True),
    sa.Column('to_authority_id', sa.Integer(), nullable=True),
    sa.Column('transfer_type', sa.Enum('surrender_to_facility', 'facility_to_adopter', 'direct_surrenderer_to_adopter', name='transfertype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'waiting_for_documents', 'waiting_for_signatures', 'ready_to_send', 'sent_to_authority', 'followup_required', 'confirmed', 'failed', 'stopped_manually', name='ownershiptransferstatus'), nullable=False),
    sa.Column('sent_to_authority_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_followup_at', sa.DateTime(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['from_authority_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['from_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['to_authority_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ownership_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ownership_transfers_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownership_transfers_next_followup_at'), ['next_followup_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownership_transfers_status'), ['status'], unique=False)

    op.create_table('surrender_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('surrenderer_person_id', sa.Integer(), nullable=False),
    sa.Column('surrender_type', sa.Enum('facility', 'full', 'home_subscription', name='surrendertype'), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('total_required_amount', sa.Float(), nullable=True),
    sa.Column('accumulated_credit', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('new_lead', 'contacted', 'waiting_for_details', 'waiting_for_payment', 'active_home_subscription', 'waiting_for_documents', 'ownership_transfer_in_progress', 'transferred_to_facility', 'available_for_adoption', 'cancelled', 'completed', name='surrenderstatus'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('privacy_required', sa.Boolean(), nullable=False),
    sa.Column('allow_direct_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['surrenderer_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surrender_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surrender_cases_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surrender_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_surrender_cases_surrenderer_person_id'), ['surrenderer_person_id'], unique=False)

    op.create_table('adoption_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('adopter_person_id', sa.Integer(), nullable=False),
    sa.Column('surrender_case_id', sa.Integer(), nullable=True),
    sa.Column('adoption_lead_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new_lead', 'screening', 'waiting_for_call', 'meeting_scheduled', 'waiting_for_decision', 'approved', 'waiting_for_signatures', 'waiting_for_documents', 'authority_submission_ready', 'sent_to_authority', 'waiting_for_authority_confirmation', 'ownership_transferred', 'completed', 'rejected', 'cancelled', name='adoptionstatus'), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('is_direct_home_adoption', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adopter_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['adoption_lead_id'], ['adoption_leads.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['surrender_case_id'], ['surrender_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adoption_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_cases_adopter_person_id'), ['adopter_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_cases_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_cases_status'), ['status'], unique=False)

    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surrender_case_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('month_index', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('payment_provider_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['surrender_case_id'], ['surrender_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_payments_surrender_case_id'), ['surrender_case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_payments_surrender_case_id'))

    op.drop_table('subscription_payments')
    with op.batch_alter_table('adoption_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_cases_status'))
        batch_op.drop_index(batch_op.f('ix_adoption_cases_dog_id'))
        batch_op.drop_index(batch_op.f('ix_adoption_cases_adopter_person_id'))

    op.drop_table('adoption_cases')
    with op.batch_alter_table('surrender_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surrender_cases_surrenderer_person_id'))
        batch_op.drop_index(batch_op.f('ix_surrender_cases_status'))
        batch_op.drop_index(batch_op.f('ix_surrender_cases_dog_id'))

    op.drop_table('surrender_cases')
    with op.batch_alter_table('ownership_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ownership_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_ownership_transfers_next_followup_at'))
        batch_op.drop_index(batch_op.f('ix_ownership_transfers_dog_id'))

    op.drop_table('ownership_transfers')
    with op.batch_alter_table('dog_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dog_photos_dog_id'))

    op.drop_table('dog_photos')
    with op.batch_alter_table('adoption_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_leads_status'))
        batch_op.drop_index(batch_op.f('ix_adoption_leads_person_id'))

    op.drop_table('adoption_leads')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_requests_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_related_entity_id'))

    op.drop_table('signature_requests')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_person_id'))

    op.drop_table('messages')
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dogs_status'))
        batch_op.drop_index(batch_op.f('ix_dogs_chip_number'))

    op.drop_table('dogs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_documents_related_entity_id'))

    op.drop_table('documents')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_phone'))
        batch_op.drop_index(batch_op.f('ix_people_city'))

    op.drop_table('people')
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipalities_city_name'))

    op.drop_table('municipalities')
    # ### end Alembic commands ###
